### ISSUE TITLE
ImportError: cannot import name 'MLP' from 'networks'

### ISSUE THREAD

**Issue by Tudouu** [HHW-zhou/TDHNN#1]
在运行main,py时候报错，您是否遗漏了MLP函数呢？
Did you miss the MLP function when running main.py?

**Comment by HHW-zhou** [comment]
> 在运行main,py时候报错，您是否遗漏了MLP函数呢？ Did you miss the MLP function when running main.py?

Thank you for paying attention to this job. I indeed overlooked the MLP class, and I have added it now.

**Comment by Tudouu** [comment]
感谢您的工作！此外，您论文中的网络叫TDHNN，但是我在您代码中只看到了HGNN相关的类命名，请问这二者是一个东西吗？
Thank you for your work! Also, the network in your paper is called TDHNN, but I only see class names related to HGNN in your code. Are these two the same thing?

**Comment by HHW-zhou** [comment]
> 感谢您的工作！此外，您论文中的网络叫TDHNN，但是我在您代码中只看到了HGNN相关的类命名，请问这二者是一个东西吗？ Thank you for your work! Also, the network in your paper is called TDHNN, but I only see class names related to HGNN in your code. Are these two the same thing?

Yes, they are the same thing.

**Comment by Tudouu** [comment]
感谢您的回复！Thank you for your response!
