### ISSUE TITLE
dataset 

### ISSUE THREAD

**Issue by WXU-M** [HHW-zhou/TDHNN#2]
Hi author, I would appreciate if you could provide the dataset for this experiment.

**Comment by HHW-zhou** [comment]
Thank you for your interest in this work. I've added some details about the work in the README, including links to the datasets. Please refer to the homepage of this repository: https://github.com/HHW-zhou/TDHNN.

**Comment by kerwinqil** [comment]
![image](https://github.com/HHW-zhou/TDHNN/assets/113840039/443aba5c-5319-42c5-a646-ad3e6dcc1e8f)
![image](https://github.com/HHW-zhou/TDHNN/assets/113840039/e95893e2-7733-4a6b-841d-a9eaf9ac7167)
你好，我什么都没有修改，直接用原本的代码和数据运行的，请问这个结果合理吗？（一位为作业发愁的本科生）
