### ISSUE TITLE
question

### ISSUE THREAD

**Issue by kerwinqil** [HHW-zhou/TDHNN#3]
![image](https://github.com/HHW-zhou/TDHNN/assets/113840039/d4dfd00c-d6c1-44d7-8c20-4c61e2633a86)
![image](https://github.com/HHW-zhou/TDHNN/assets/113840039/42181170-6253-466b-ad8b-9ac37dc44f18)

你好，我什么都没有修改，直接用原本的代码和数据运行的，请问这个结果合理吗？（一位为作业发愁的本科生）

**Comment by HHW-zhou** [comment]
合理的。论文中报道的准确度偏低。

**Comment by kerwinqil** [comment]
谢谢
